// Generated by gencpp from file msg_pkg/srv_data.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_SRV_DATA_H
#define MSG_PKG_MESSAGE_SRV_DATA_H

#include <ros/service_traits.h>


#include <msg_pkg/srv_dataRequest.h>
#include <msg_pkg/srv_dataResponse.h>


namespace msg_pkg
{

struct srv_data
{

typedef srv_dataRequest Request;
typedef srv_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_data
} // namespace msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msg_pkg::srv_data > {
  static const char* value()
  {
    return "cc658ab5d7c21e947d19ff1a924c551f";
  }

  static const char* value(const ::msg_pkg::srv_data&) { return value(); }
};

template<>
struct DataType< ::msg_pkg::srv_data > {
  static const char* value()
  {
    return "msg_pkg/srv_data";
  }

  static const char* value(const ::msg_pkg::srv_data&) { return value(); }
};


// service_traits::MD5Sum< ::msg_pkg::srv_dataRequest> should match
// service_traits::MD5Sum< ::msg_pkg::srv_data >
template<>
struct MD5Sum< ::msg_pkg::srv_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msg_pkg::srv_data >::value();
  }
  static const char* value(const ::msg_pkg::srv_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_pkg::srv_dataRequest> should match
// service_traits::DataType< ::msg_pkg::srv_data >
template<>
struct DataType< ::msg_pkg::srv_dataRequest>
{
  static const char* value()
  {
    return DataType< ::msg_pkg::srv_data >::value();
  }
  static const char* value(const ::msg_pkg::srv_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msg_pkg::srv_dataResponse> should match
// service_traits::MD5Sum< ::msg_pkg::srv_data >
template<>
struct MD5Sum< ::msg_pkg::srv_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msg_pkg::srv_data >::value();
  }
  static const char* value(const ::msg_pkg::srv_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_pkg::srv_dataResponse> should match
// service_traits::DataType< ::msg_pkg::srv_data >
template<>
struct DataType< ::msg_pkg::srv_dataResponse>
{
  static const char* value()
  {
    return DataType< ::msg_pkg::srv_data >::value();
  }
  static const char* value(const ::msg_pkg::srv_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSG_PKG_MESSAGE_SRV_DATA_H
