(cl:in-package msg_pkg-msg)
(cl:export '(DATA-VAL
          DATA
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          X_POS-VAL
          X_POS
          Y_POS-VAL
          Y_POS
          Z_POS-VAL
          Z_POS
          X_IK_POS-VAL
          X_IK_POS
          Y_IK_POS-VAL
          Y_IK_POS
          Z_IK_POS-VAL
          Z_IK_POS
          Z_DEPTH-VAL
          Z_DEPTH
          POS_FLAG-VAL
          POS_FLAG
          DEPTH_FLAG-VAL
          DEPTH_FLAG
          F64_LINEAR_X-VAL
          F64_LINEAR_X
          F64_LINEAR_Y-VAL
          F64_LINEAR_Y
          F64_LINEAR_Z-VAL
          F64_LINEAR_Z
          F64_ANGULAR_X-VAL
          F64_ANGULAR_X
          F64_ANGULAR_Y-VAL
          F64_ANGULAR_Y
          F64_ANGULAR_Z-VAL
          F64_ANGULAR_Z
))