float64 linear_x
float64 linear_y
float64 linear_z
float64 angular_x
float64 angular_y
float64 angular_z
---
float64 linear_x_result
float64 linear_y_result
float64 linear_z_result
float64 angular_x_result
float64 angular_y_result
float64 angular_z_result
