# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_pkg/srv_dataRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class srv_dataRequest(genpy.Message):
  _md5sum = "3ac58878d00f42fbc731fa86d45253b5"
  _type = "msg_pkg/srv_dataRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 linear_x
float64 linear_y
float64 linear_z
float64 angular_x
float64 angular_y
float64 angular_z
"""
  __slots__ = ['linear_x','linear_y','linear_z','angular_x','angular_y','angular_z']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linear_x,linear_y,linear_z,angular_x,angular_y,angular_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(srv_dataRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linear_x is None:
        self.linear_x = 0.
      if self.linear_y is None:
        self.linear_y = 0.
      if self.linear_z is None:
        self.linear_z = 0.
      if self.angular_x is None:
        self.angular_x = 0.
      if self.angular_y is None:
        self.angular_y = 0.
      if self.angular_z is None:
        self.angular_z = 0.
    else:
      self.linear_x = 0.
      self.linear_y = 0.
      self.linear_z = 0.
      self.angular_x = 0.
      self.angular_y = 0.
      self.angular_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_x, _x.linear_y, _x.linear_z, _x.angular_x, _x.angular_y, _x.angular_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_x, _x.linear_y, _x.linear_z, _x.angular_x, _x.angular_y, _x.angular_z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_x, _x.linear_y, _x.linear_z, _x.angular_x, _x.angular_y, _x.angular_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_x, _x.linear_y, _x.linear_z, _x.angular_x, _x.angular_y, _x.angular_z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_pkg/srv_dataResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class srv_dataResponse(genpy.Message):
  _md5sum = "009ac2610164615dbdb217c747ffcb0f"
  _type = "msg_pkg/srv_dataResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 linear_x_result
float64 linear_y_result
float64 linear_z_result
float64 angular_x_result
float64 angular_y_result
float64 angular_z_result

"""
  __slots__ = ['linear_x_result','linear_y_result','linear_z_result','angular_x_result','angular_y_result','angular_z_result']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linear_x_result,linear_y_result,linear_z_result,angular_x_result,angular_y_result,angular_z_result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(srv_dataResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linear_x_result is None:
        self.linear_x_result = 0.
      if self.linear_y_result is None:
        self.linear_y_result = 0.
      if self.linear_z_result is None:
        self.linear_z_result = 0.
      if self.angular_x_result is None:
        self.angular_x_result = 0.
      if self.angular_y_result is None:
        self.angular_y_result = 0.
      if self.angular_z_result is None:
        self.angular_z_result = 0.
    else:
      self.linear_x_result = 0.
      self.linear_y_result = 0.
      self.linear_z_result = 0.
      self.angular_x_result = 0.
      self.angular_y_result = 0.
      self.angular_z_result = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_x_result, _x.linear_y_result, _x.linear_z_result, _x.angular_x_result, _x.angular_y_result, _x.angular_z_result))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_x_result, _x.linear_y_result, _x.linear_z_result, _x.angular_x_result, _x.angular_y_result, _x.angular_z_result,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_x_result, _x.linear_y_result, _x.linear_z_result, _x.angular_x_result, _x.angular_y_result, _x.angular_z_result))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_x_result, _x.linear_y_result, _x.linear_z_result, _x.angular_x_result, _x.angular_y_result, _x.angular_z_result,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
class srv_data(object):
  _type          = 'msg_pkg/srv_data'
  _md5sum = 'cc658ab5d7c21e947d19ff1a924c551f'
  _request_class  = srv_dataRequest
  _response_class = srv_dataResponse
